version: build-{build}
image:
- Visual Studio 2015
platform:
- x64
environment:
  matrix:
    - MINICONDA: C:\Miniconda3-x64
init:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
build_script:
  - git submodule update --init
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda install pip tbb tbb-devel
  - conda install --file requirements-testing.txt
  - "set TBB_INCLUDE=%MINICONDA%\\Library\\include"
  - "set TBB_LINK=%MINICONDA%\\Library\\lib"
  - python --version
  - python setup.py build_ext --inplace
test_script:
  - python -m unittest discover tests -v
